-- 车队管理相关表结构

-- 车辆表
CREATE TABLE IF NOT EXISTS vehicles (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  userId BIGINT UNSIGNED NOT NULL COMMENT '所属用户ID',
  brand VARCHAR(100) NOT NULL COMMENT '品牌',
  horsepower VARCHAR(50) NOT NULL COMMENT '马力',
  loadCapacity VARCHAR(50) NOT NULL COMMENT '载重',
  axleCount INT NOT NULL COMMENT '轴数',
  tireCount INT NOT NULL COMMENT '轮胎数量',
  trailerLength VARCHAR(50) NOT NULL COMMENT '挂车长度',
  certificateImages JSON COMMENT '证件图片URL数组',
  otherImages JSON COMMENT '其它图片URL数组',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_userId (userId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='车辆信息表';

-- 货运记录表
CREATE TABLE IF NOT EXISTS transport_records (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  vehicleId BIGINT UNSIGNED NOT NULL COMMENT '车辆ID',
  goodsName VARCHAR(200) NOT NULL COMMENT '货物名称',
  date DATE NOT NULL COMMENT '日期',
  freight DECIMAL(10,2) DEFAULT 0 COMMENT '运费',
  otherIncome DECIMAL(10,2) DEFAULT 0 COMMENT '其它费用',
  fuelCost DECIMAL(10,2) DEFAULT 0 COMMENT '油费',
  repairCost DECIMAL(10,2) DEFAULT 0 COMMENT '维修费',
  accommodationCost DECIMAL(10,2) DEFAULT 0 COMMENT '住宿费',
  mealCost DECIMAL(10,2) DEFAULT 0 COMMENT '饭费',
  otherExpense DECIMAL(10,2) DEFAULT 0 COMMENT '其它费用',
  remark TEXT COMMENT '备注',
  images JSON COMMENT '图片URL数组',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_vehicleId (vehicleId),
  INDEX idx_date (date),
  FOREIGN KEY (vehicleId) REFERENCES vehicles(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='货运记录表';

-- 证件分享 Token 表
CREATE TABLE IF NOT EXISTS certificate_share_tokens (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  token VARCHAR(100) UNIQUE NOT NULL COMMENT '分享token',
  vehicleId BIGINT UNSIGNED NOT NULL COMMENT '车辆ID',
  expireAt DATETIME NOT NULL COMMENT '过期时间',
  useCount INT UNSIGNED DEFAULT 0 COMMENT '使用次数',
  maxUseCount INT UNSIGNED DEFAULT NULL COMMENT '最大使用次数（NULL表示无限制）',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_token (token),
  INDEX idx_expireAt (expireAt),
  FOREIGN KEY (vehicleId) REFERENCES vehicles(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='证件分享Token表';

